// Mocks generated by Mockito 5.4.6 from annotations
// in bond_up_mobile/test/features/leaderboard/data/services/leaderboard_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pbp_django_auth/pbp_django_auth.dart' as _i3;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CookieRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockCookieRequest extends _i1.Mock implements _i3.CookieRequest {
  MockCookieRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, _i3.Cookie> get cookies => (super.noSuchMethod(
        Invocation.getter(#cookies),
        returnValue: <String, _i3.Cookie>{},
      ) as Map<String, _i3.Cookie>);

  @override
  Map<String, dynamic> get jsonData => (super.noSuchMethod(
        Invocation.getter(#jsonData),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.SharedPreferences get local => (super.noSuchMethod(
        Invocation.getter(#local),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#local),
        ),
      ) as _i2.SharedPreferences);

  @override
  bool get loggedIn => (super.noSuchMethod(
        Invocation.getter(#loggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  set headers(Map<String, String>? value) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set cookies(Map<String, _i3.Cookie>? value) => super.noSuchMethod(
        Invocation.setter(
          #cookies,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set jsonData(Map<String, dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #jsonData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set local(_i2.SharedPreferences? value) => super.noSuchMethod(
        Invocation.setter(
          #local,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loggedIn(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #loggedIn,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set initialized(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #initialized,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<dynamic> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> persist(String? cookies) => (super.noSuchMethod(
        Invocation.method(
          #persist,
          [cookies],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> login(
    String? url,
    dynamic data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            url,
            data,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  Map<String, dynamic> getJsonData() => (super.noSuchMethod(
        Invocation.method(
          #getJsonData,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<dynamic> get(String? url) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> post(
    String? url,
    dynamic data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            url,
            data,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> postJson(
    String? url,
    dynamic data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postJson,
          [
            url,
            data,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> logout(String? url) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [url],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
